import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;

public class EnglishIndonesia extends javax.swing.JFrame {
    private Map<String, String> kata = new HashMap<String, String>();
    private JTextField tfword;
    private JButton translateButton;
    private JTextArea taword;
    private JButton switchLanguageButton;
    private JButton exitButton;
    private JPanel InggrisIndonesiaPanel;
    private JLabel statusBar;
    private JFrame exit;
    private static JFrame frame;

    public void setKata(String a, String b){
        kata.put(a,b);
    }

    public Map<String, String> getKata(){
        return this.kata;
    }

    public EnglishIndonesia() {
        setKata("abandoned","terlantar");
        setKata("absurd","konyol");
        setKata("accurate","tepat");
        setKata("adorable","menarik");
        setKata("afraid","takut");
        setKata("agreeable","serasi");
        setKata("alive","hidup");
        setKata("amazing","menakjubkan");
        setKata("ambiguous","ambigu");
        setKata("amused","terhibur");
        setKata("ancient","kuno");
        setKata("angry","marah");
        setKata("annoying","menjengkelkan");
        setKata("anxious","gelisah");
        setKata("arrogant","sombong");
        setKata("ashamed","malu");
        setKata("awesome","mengagumkan");
        setKata("awful","mengerikan");
        setKata("authentic","asli");
        setKata("awkward","canggung");
        setKata("bad","buruk");
        setKata("back","kembali");
        setKata("basic","dasar");
        setKata("beautiful","indah");
        setKata("better","lebih baik");
        setKata("best","terbaik");
        setKata("big","besar");
        setKata("bitter","pahit");
        setKata("blank","kosong");
        setKata("blind","buta");
        setKata("blissful","penuh kebahagiaan");
        setKata("boring","membosankan");
        setKata("brave","berani");
        setKata("bright","terang");
        setKata("broken","rusak");
        setKata("bumpy","bergelombang");
        setKata("busy","sibuk");
        setKata("calm","tenang");
        setKata("carefree","riang");
        setKata("careful","cermat");
        setKata("careless","ceroboh");
        setKata("caring","peduli");
        setKata("cautious","waspada");
        setKata("chubby","tembem");
        setKata("clean","bersih");
        setKata("clear","jelas");
        setKata("cloudy","berawan");
        setKata("clueless","tidak berpengetahuan");
        setKata("cold","dingin");
        setKata("colorful","warna warni");
        setKata("comfortable","nyaman");
        setKata("complicated","rumit");
        setKata("crazy","gila");
        setKata("creamy","lembut");
        setKata("curly","keriting");
        setKata("dangerous","berbahaya");
        setKata("darling","sayang");
        setKata("dark","gelap");
        setKata("dearest","yang tersayang");
        setKata("deep","dalam");
        setKata("delicious","lezat");
        setKata("delightful","menyenangkan");
        setKata("different","berbeda");
        setKata("difficult","sulit");
        setKata("dirty","kotor");
        setKata("disguised","disamarkan");
        setKata("dizzy","pusing");
        setKata("dramatic","dramatis");
        setKata("dry","kering");
        setKata("dull","membosankan, kusam");
        setKata("distant","jauh");
        setKata("early","awal");
        setKata("easy","mudah");
        setKata("easy going","mudah bergaul");
        setKata("edible","dapat dimakan");
        setKata("elastic","elastis");
        setKata("empty","kosong");
        setKata("enchanted","terpesona");
        setKata("entire","seluruh");
        setKata("equal","sama");
        setKata("essential","penting");
        setKata("evil","jahat");
        setKata("excellent","unggul");
        setKata("expensive","mahal");
        setKata("expert","ahli");
        setKata("elegant","anggun");
        setKata("fabulous","menakjubkan");
        setKata("fair","adil");
        setKata("faint","lemah, redup");
        setKata("faithful","setia");
        setKata("false","salah");
        setKata("familiar","akrab");
        setKata("famous","terkenal");
        setKata("fancy","indah");
        setKata("far","jauh");
        setKata("fast","cepat");
        setKata("fearless","tak kenal takut");
        setKata("fine","baik");
        setKata("flat","datar");
        setKata("fluffy","halus");
        setKata("foolish","bodoh");
        setKata("free","bebas");
        setKata("funny","lucu");
        setKata("frizzy","keriting");
        setKata("general","umum");
        setKata("generous","murah hati");
        setKata("gentle","lemah lembut");
        setKata("giant","raksasa");
        setKata("gloomy","suram");
        setKata("glossy","berkilau");
        setKata("good","baik");
        setKata("graceful","anggun");
        setKata("grateful","bersyukur, berterimakasih");
        setKata("great","besar, hebat");
        setKata("gross","kotor");
        setKata("grumpy","pemarah");
        setKata("guilty","merasa bersalah");
        setKata("glorious","mulia");
        setKata("genuine","asli");
        setKata("glittering","cemerlang");
        setKata("grimy","kotor");
        setKata("gullible","mudah tertipu");
        setKata("hairy","berbulu");
        setKata("half","setengah");
        setKata("handsome","tampan");
        setKata("happy","senang, bahagia");
        setKata("harmful","berbahaya");
        setKata("harmless","tidak berbahaya");
        setKata("harsh","keras, kasar, kejam");
        setKata("hasty","gegabah");
        setKata("healthy","sehat");
        setKata("hidden","tersembunyi");
        setKata("hideous","mengerikan");
        setKata("high","tinggi");
        setKata("hilarious","riang");
        setKata("honest","jujur");
        setKata("horrible","mengerikan");
        setKata("hot","panas");
        setKata("hungry","lapar");
        setKata("humble","rendah hati, sederhana");
        setKata("huge","besar");
        setKata("icy","dingin, licin karena es, tidak ramah");
        setKata("ill","sakit");
        setKata("imperfect","cacat");
        setKata("important","penting");
        setKata("impossible","mustahil");
        setKata("impressive","hebat, impresif, keren");
        setKata("incredible","luar biasa");
        setKata("innocent","tidak bersalah");
        setKata("itchy","gatal");
        setKata("intelligent","cerdas");
        setKata("instructive","edukatif");
        setKata("insignificant","sepele");
        setKata("jammed","macet");
        setKata("jangling","berdenting");
        setKata("jarring","menggelegar, gemuruh");
        setKata("jawless","tanpa rahang");
        setKata("jealous","cemburu");
        setKata("jobless","tidak punya pekerjaan");
        setKata("joyful","riang");
        setKata("joyless","tanpa kegembiraan");
        setKata("judgemental","menghakimi");
        setKata("juicy","berair");
        setKata("juvenile","remaja, muda");
        setKata("justifiable","dapat dibenarkan");
        setKata("judicious","bijaksana");
        setKata("kept","disimpan");
        setKata("key","utama, penting, pokok");
        setKata("kind","baik, manis, baik hati");
        setKata("kindly","penyayang, murah hati");
        setKata("knightly","berani, pemurah");
        setKata("knobby","menonjol");
        setKata("knotty","rumit");
        setKata("known","terkemuka, termasyur, terkenal");
        setKata("kindled","menyala");
        setKata("kindhearted","baik hati");
        setKata("keyed","bersemangat");
        setKata("keen","tajam, tekun, bersemangat");
        setKata("kittenish","genit");
        setKata("knackered","lelah");
        setKata("live","hidup");
        setKata("labeled","berlabel, yang dinamakan");
        setKata("lethargic","lesu");
        setKata("lean","kurus, buruk, tak berlemak");
        setKata("laborious","melelahkan");
        setKata("lacking","kurang");
        setKata("lacy","renda");
        setKata("landless","tak bertanah");
        setKata("lanky","kurus, semampai");
        setKata("large","besar");
        setKata("last","terakhir");
        setKata("late","terlambat");
        setKata("latest","terbaru");
        setKata("lawful","sah");
        setKata("lazy","malas");
        setKata("mad","marah, gila");
        setKata("majestic","megah, agung");
        setKata(",major","utama, besar");
        setKata("marvelous","menakjubkan");
        setKata("massive","besar besaran");
        setKata("mean","jahat, licik");
        setKata("melodic","merdu");
        setKata("messy","kacau, berantakan");
        setKata("mild","ringan");
        setKata("minor","kecil");
        setKata("miserable","sedih");
        setKata("motionless","diam");
        setKata("mortified","malu");
        setKata("naughty","nakal");
        setKata("near","dekat");
        setKata("neat","rapi");
        setKata("necessary","perlu");
        setKata("new","baru");
        setKata("nervous","gugup");
        setKata("nice","bagus, baik");
        setKata("noisy","berisik, ribut");
        setKata("notable","penting");
        setKata("nutritious","bergizi");
        setKata("numb","mati rasa");
        setKata("obese","gendut");
        setKata("oily","berminyak");
        setKata("obvious","jelas");
        setKata("odd","aneh");
        setKata("offensive","menghina, menyakiti hati");
        setKata("old","tua");
        setKata("open","buka, lepas");
        setKata("original","asli");
        setKata("overdue","terlambat");
        setKata("own","kepunyaan sendiri");
        setKata("ownerless","tanpa pemilik");
        setKata("overcooked","terlalu matang");
        setKata("outlandish","aneh");
        setKata("outstanding","terkemuka");
        setKata("outrageous","memalukan");
        setKata("pale","pucat, pudar");
        setKata("passionate","bergairah");
        setKata("past","lalu, lampau");
        setKata("peaceful","tenang");
        setKata("perfect","sempurna");
        setKata("plain","polos");
        setKata("playful","ceria");
        setKata("pleasant","nyaman");
        setKata("polite","sopan");
        setKata("poor","miskin");
        setKata("possible","mungkin");
        setKata("powerful","kuasa, manjur");
        setKata("present","sekarang, kini");
        setKata("pretty","cantik");
        setKata("qualified","berkualitas");
        setKata("queasy","mual, muak, mau muntah");
        setKata("querulous","suka mengeluh");
        setKata("quick","cepat");
        setKata("quiet","diam");
        setKata("quirky","unik");
        setKata("ragged","kasar");
        setKata("rare","langka, jarang");
        setKata("rash","gegabah");
        setKata("raw","mentah");
        setKata("recent","baru");
        setKata("reckless","ceroboh");
        setKata("real","nyata");
        setKata("ready","siap");
        setKata("reasonable","masuk akal");
        setKata("required","wajib");
        setKata("respectful","hormat");
        setKata("responsible","tanggung jawab");
        setKata("rich","kaya");
        setKata("ripe","matang");
        setKata("rotten","busuk");
        setKata("sad","sedih");
        setKata("safe","aman");
        setKata("salty","asin");
        setKata("same","sama");
        setKata("sarcastic","tajam");
        setKata("satisfied","puas");
        setKata("scary","mengerikan");
        setKata("scented","wangi");
        setKata("selfish","egois");
        setKata("separate","terpisah");
        setKata("shallow","dangkal");
        setKata("shameful","memalukan");
        setKata("shameless","tak tahu malu");
        setKata("sharp","tajam");
        setKata("shimmering","berkilauan");
        setKata("shiny","berkilau");
        setKata("short","pendek");
        setKata("sick","sakit");
        setKata("thoughtful","bijaksana");
        setKata("terrific","hebat");
        setKata("thick","tebal");
        setKata("thin","tipis, kurus");
        setKata("tidy","rapi");
        setKata("thunderous","gemuruh");
        setKata("tiny","kecil, mungil");
        setKata("tough","sulit, tabah");
        setKata("tall","tinggi");
        setKata("talkative","latah, banyak bicara, cerewet");
        setKata("tame","jinak");
        setKata("tasty","lezat");
        setKata("tense","tegang");
        setKata("thankful","berterimakasih");
        setKata("thirsty","haus");
        setKata("ugly","jelek");
        setKata("unacceptable","tidak dapat diterima");
        setKata("undercover","rahasia, tersembunyi");
        setKata("uneasy","gelisah, khawatir, tak tenang");
        setKata("uneven","tidak rata");
        setKata("unfair","tidak adil");
        setKata("vacant","kosong");
        setKata("vain","sia sia, sombong, angkuh");
        setKata("valuable","berharga");
        setKata("versatile","serba guna");
        setKata("warm","hangat");
        setKata("wavy","bergelombang");
        setKata("weak","lemah");
        setKata("weird","aneh");
        setKata("wet","basah");
        setKata("whole","seluruh");
        setKata("wicked","jahat");
        setKata("wide","lebar");
        setKata("wild","liar");
        setKata("wise","bijaksana");
        setKata("worn","usang");
        setKata("worse","lebih buruk");
        setKata("young","muda");
        setKata("eat","makan");
        setKata("sleep","tidur");
        setKata("stand up","berdiri");
        setKata("sit down","duduk");
        setKata("walk","berjalan");
        setKata("drink","minum");
        setKata("write","menulis");
        setKata("read","membaca");
        setKata("wash","mencuci");
        setKata("work","bekerja");
        setKata("come","datang");
        setKata("wake up","bangun");
        setKata("take a bath","mandi");
        setKata("take a pee","pipis");
        setKata("take a dump","buang air besar");
        setKata("speak","berbicara");
        setKata("talk","mengobrol");
        setKata("think","berpikir");
        setKata("tell","menceritakan, memberitahu");
        setKata("listen","mendengarkan");
        setKata("wear","memakai");
        setKata("use","menggunakan");
        setKata("want","menginginkan");
        setKata("go","pergi");
        setKata("call","memanggil");
        setKata("go work","pergi kerja");
        setKata("go home","pulang");
        setKata("go shopping","belanja");
        setKata("date","pacaran, kencan");
        setKata("understand","mengerti");
        setKata("cough","batuk");
        setKata("cook","memasak");
        setKata("fry","menggoreng");
        setKata("buy","membeli");
        setKata("sell","menjual");
        setKata("pay","membayar");
        setKata("open","membuka");
        setKata("close","menutup");
        setKata("give","memberi");
        setKata("have","memiliki");
        setKata("throw","membuang");
        setKata("show","menunjukkan");
        setKata("decrease","mengurangi");
        setKata("add","menambahkan");
        setKata("cut","memotong");
        setKata("connect","menghubungkan");
        setKata("arrive","tiba");
        setKata("leave","meninggalkan");
        setKata("remember","mengingat");
        setKata("ask","bertanya, meminta");
        setKata("answer","jawaban");
        setKata("need","membutuhkan, memerlukan");
        setKata("put","meletakkan");
        setKata("scream","teriak");
        setKata("shout","berteriak");
        setKata("cry","menangis");
        setKata("laugh","tertawa");
        setKata("live","tinggal");
        setKata("pray","berdoa");
        setKata("push","dorong");
        setKata("pull","tarik");
        setKata("teach","mengajar");
        setKata("study","belajar");
        setKata("wait","menunggu");
        setKata("help","menolong");
        setKata("swim","berenang");
        setKata("meet","bertemu");
        setKata("drive","mengendarai (mobil)");
        setKata("ride","mengendarai (motor)");
        setKata("borrow","meminjam");
        setKata("lend","meminjamkan");
        setKata("return","mengembalikan");
        setKata("find","menemukan");
        setKata("hide","menyembunyikan");
        setKata("disturb","mengganggu");
        setKata("motivate","memotivasi");
        setKata("look for","mencari");
        setKata("look at, see","melihat");
        setKata("clean","bersih");
        setKata("sweep","menyapu");
        setKata("mop","mengepel");
        setKata("paint","mengecat");
        setKata("visit","mengunjungi");
        setKata("invite","mengundang");
        setKata("make","membuat");
        setKata("save","menyimpan");
        setKata("move","bergerak");
        setKata("face","wajah");
        setKata("imagine","membayangkan");
        setKata("dance","menari");
        setKata("sing","menyanyi");


        translateButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String inputText = tfword.getText();

                if (getKata().containsKey(inputText)) {
                    taword.setText(kata.get(inputText));
                }else {
                    taword.setText(getKata().get(inputText));
                    JOptionPane.showMessageDialog(frame, inputText+" is not in the smart dictionary");
                }
            }
        });

        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int konfirmasi = JOptionPane.showConfirmDialog(exit, "Are you sure you want to quit?", "Please choose", JOptionPane.YES_NO_OPTION);
                if (konfirmasi == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(exit, "Thank you for using the SMART DICTIONARY!");
                    System.exit(0); }
            }
        });

        switchLanguageButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                IndonesiaEnglish ei = new IndonesiaEnglish();
                ei.showIndEng();
                frame.setVisible(false);
            }
        });
    }

    public static void showEngInd(){
        frame = new JFrame("Inggris --> Indonesia");
        frame.setContentPane(new EnglishIndonesia().InggrisIndonesiaPanel);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        showEngInd();
    }
}
