import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;

public class IndonesiaEnglish extends javax.swing.JFrame {
    private Map<String, String> kata = new HashMap<String, String>();
    private JPanel IndonesiaInggrisPanel;
    private JTextField tfkata;
    private JTextArea takata;
    private JButton terjemahkanButton;
    private JButton tukarBahasaButton;
    private JButton keluarButton;
    private JLabel statusBar;
    private JFrame keluar;
    private static JFrame frame;

    public void setKata(String a, String b) {
        kata.put(a,b);
    }

    public Map<String, String> getKata() {
        return this.kata;
    }

    public IndonesiaEnglish() {
        setKata("terlantar","abandoned");
        setKata("konyol","absurd");
        setKata("tepat","accurate");
        setKata("menarik","adorable");
        setKata("takut","afraid");
        setKata("serasi","agreeable");
        setKata("hidup","alive");
        setKata("menakjubkan","amazing");
        setKata("ambigu","ambiguous");
        setKata("terhibur","amused");
        setKata("kuno","ancient");
        setKata("marah","angry, mad");
        setKata("menjengkelkan","annoying");
        setKata("gelisah","anxious, uneasy");
        setKata("sombong","arrogant");
        setKata("malu","ashamed");
        setKata("mengagumkan","awesome");
        setKata("mengerikan","awful");
        setKata("asli","authentic");
        setKata("canggung","awkward");
        setKata("buruk","bad");
        setKata("kembali","back");
        setKata("dasar","basic");
        setKata("indah","beautiful");
        setKata("lebih baik","better");
        setKata("terbaik","best");
        setKata("besar","big");
        setKata("pahit","bitter");
        setKata("kosong","blank, empty");
        setKata("buta","blind");
        setKata("penuh kebahagiaan","blissful");
        setKata("membosankan","boring");
        setKata("berani","brave");
        setKata("terang","bright");
        setKata("rusak","broken");
        setKata("bergelombang","bumpy");
        setKata("sibuk","busy");
        setKata("tenang","calm");
        setKata("riang","carefree");
        setKata("cermat","careful");
        setKata("ceroboh","careless");
        setKata("peduli","caring");
        setKata("waspada","cautious");
        setKata("tembem","chubby");
        setKata("bersih","clean");
        setKata("jelas","clear");
        setKata("berawan","cloudy");
        setKata("tidak berpengetahuan","clueless");
        setKata("dingin","cold");
        setKata("warna warni","colorful");
        setKata("nyaman","comfortable");
        setKata("rumit","complicated");
        setKata("gila","crazy, mad");
        setKata("lembut","creamy");
        setKata("keriting","curly");
        setKata("berbahaya","dangerous");
        setKata("sayang","darling");
        setKata("gelap","dark");
        setKata("yang tersayang","dearest");
        setKata("dalam","deep");
        setKata("lezat","delicious");
        setKata("menyenangkan","delightful");
        setKata("berbeda","different");
        setKata("sulit","difficult");
        setKata("kotor","dirty, gross, grimy");
        setKata("disamarkan","disguised");
        setKata("pusing","dizzy");
        setKata("dramatis","dramatic");
        setKata("kering","dry");
        setKata("membosankan","dull");
        setKata("jauh","distant");
        setKata("awal","early");
        setKata("mudah","easy");
        setKata("mudah bergaul","easy going");
        setKata("dapat dimakan","edible");
        setKata("elastis","elastic");
        setKata("kosong","empty");
        setKata("terpesona","enchanted");
        setKata("seluruh","entire");
        setKata("sama","equal");
        setKata("penting","essential");
        setKata("jahat","evil");
        setKata("unggul","excellent");
        setKata("mahal","expensive");
        setKata("ahli","expert");
        setKata("anggun","elegant");
        setKata("menakjubkan","fabulous");
        setKata("adil","fair");
        setKata("lemah","faint");
        setKata("setia","faithful");
        setKata("salah","false");
        setKata("akrab","familiar");
        setKata("terkenal","famous");
        setKata("indah","fancy");
        setKata("jauh","far");
        setKata("cepat","fast");
        setKata("tak kenal takut","fearless");
        setKata("baik","fine");
        setKata("datar","flat");
        setKata("halus","fluffy");
        setKata("bodoh","foolish");
        setKata("bebas","free");
        setKata("lucu","funny");
        setKata("keriting","frizzy");
        setKata("umum","general");
        setKata("murah hati","generous");
        setKata("lemah lembut","gentle");
        setKata("raksasa","giant");
        setKata("suram","gloomy");
        setKata("berkilau","glossy");
        setKata("baik","good");
        setKata("anggun","graceful");
        setKata("bersyukur","grateful");
        setKata("besar, hebat","great");
        setKata("pemarah","grumpy");
        setKata("merasa bersalah","guilty");
        setKata("mulia","glorious");
        setKata("asli","genuine");
        setKata("cemerlang","glittering");
        setKata("mudah tertipu","gullible");
        setKata("berbulu","hairy");
        setKata("setengah","half");
        setKata("tampan","handsome");
        setKata("senang, bahagia","happy");
        setKata("berbahaya","harmful");
        setKata("tidak berbahaya","harmless");
        setKata("kasar","harsh");
        setKata("gegabah","hasty");
        setKata("sehat","healthy");
        setKata("tersembunyi","hidden");
        setKata("mengerikan","hideous");
        setKata("tinggi","high");
        setKata("riang","hilarious");
        setKata("jujur","honest");
        setKata("mengerikan","horrible");
        setKata("panas","hot");
        setKata("lapar","hungry");
        setKata("rendah hati, sederhana","humble");
        setKata("besar","huge");
        setKata("dingin, licin karena es, tidak ramah","icy");
        setKata("sakit","ill");
        setKata("cacat","imperfect");
        setKata("penting","important");
        setKata("mustahil","impossible");
        setKata("hebat, impresif, keren","impressive");
        setKata("luar biasa","incredible");
        setKata("tidak bersalah","innocent");
        setKata("gatal","itchy");
        setKata("cerdas","intelligent");
        setKata("edukatif","instructive");
        setKata("sepele","insignificant");
        setKata("macet","jammed");
        setKata("berdenting","jangling");
        setKata("menggelegar, gemuruh","jarring");
        setKata("tanpa rahang","jawless");
        setKata("cemburu","jealous");
        setKata("tidak punya pekerjaan","jobless");
        setKata("riang","joyful");
        setKata("tanpa kegembiraan","joyless");
        setKata("menghakimi","judgemental");
        setKata("berair","juicy");
        setKata("remaja","juvenile");
        setKata("dapat dibenarkan","justifiable");
        setKata("bijaksana","judicious");
        setKata("disimpan","kept");
        setKata("utama","key, major");
        setKata("baik","kind");
        setKata("penyayang","kindly");
        setKata("berani","knightly");
        setKata("menonjol","knobby");
        setKata("rumit","knotty");
        setKata("terkemuka","known");
        setKata("menyala","kindled");
        setKata("baik hati","kindhearted");
        setKata("bersemangat","keyed");
        setKata("tajam","keen");
        setKata("genit","kittenish");
        setKata("lelah","knackered");
        setKata("hidup","live");
        setKata("berlabel","labeled");
        setKata("lesu","lethargic");
        setKata("kurus","lean, lanky");
        setKata("melelahkan","laborious");
        setKata("kurang","lacking");
        setKata("renda","lacy");
        setKata("tak bertanah","landless");
        setKata("besar","large");
        setKata("terakhir","last");
        setKata("terlambat","late");
        setKata("terbaru","latest");
        setKata("sah","lawful");
        setKata("malas","lazy");
        setKata("megah","majestic");
        setKata("menakjubkan","marvelous");
        setKata("besar besaran","massive");
        setKata("jahat","mean");
        setKata("merdu","melodic");
        setKata("kacau","messy");
        setKata("ringan","mild");
        setKata("kecil","minor");
        setKata("sedih","miserable");
        setKata("diam","motionless");
        setKata("malu","mortified");
        setKata("nakal","naughty");
        setKata("dekat","near");
        setKata("rapi","neat");
        setKata("perlu","necessary");
        setKata("baru","new");
        setKata("gugup","nervous");
        setKata("bagus","nice");
        setKata("berisik","noisy");
        setKata("penting","notable");
        setKata("bergizi","nutritious");
        setKata("mati rasa","numb");
        setKata("gendut","obese");
        setKata("berminyak","oily");
        setKata("jelas","obvious");
        setKata("aneh","odd");
        setKata("menghina","offensive");
        setKata("tua","old");
        setKata("buka, lepas","open");
        setKata("asli","original");
        setKata("terlambat","overdue");
        setKata("kepunyaan sendiri","own");
        setKata("tanpa pemilik","ownerless");
        setKata("terlalu matang","overcooked");
        setKata("aneh","outlandish");
        setKata("terkemuka","outstanding");
        setKata("memalukan","outrageous");
        setKata("pucat","pale");
        setKata("bergairah","passionate");
        setKata("lalu, lampau","past");
        setKata("tenang","peaceful");
        setKata("sempurna","perfect");
        setKata("polos","plain");
        setKata("ceria","playful");
        setKata("nyaman","pleasant");
        setKata("sopan","polite");
        setKata("miskin","poor");
        setKata("mungkin","possible");
        setKata("kuasa","powerful");
        setKata("sekarang","present");
        setKata("cantik","pretty");
        setKata("berkualitas","qualified");
        setKata("mual","queasy");
        setKata("suka mengeluh","querulous");
        setKata("cepat","quick");
        setKata("diam","quiet");
        setKata("unik","quirky");
        setKata("kasar","ragged");
        setKata("langka","rare");
        setKata("gegabah","rash");
        setKata("mentah","raw");
        setKata("baru","recent");
        setKata("ceroboh","reckless");
        setKata("nyata","real");
        setKata("siap","ready");
        setKata("masuk akal","reasonable");
        setKata("wajib","required");
        setKata("hormat","respectful");
        setKata("tanggung jawab","responsible");
        setKata("kaya","rich");
        setKata("matang","ripe");
        setKata("busuk","rotten");
        setKata("sedih","sad");
        setKata("aman","safe");
        setKata("asin","salty");
        setKata("sama","same");
        setKata("tajam","sarcastic");
        setKata("puas","satisfied");
        setKata("mengerikan","scary");
        setKata("wangi","scented");
        setKata("egois","selfish");
        setKata("terpisah","separate");
        setKata("dangkal","shallow");
        setKata("memalukan","shameful");
        setKata("tak tahu malu","shameless");
        setKata("tajam","sharp");
        setKata("berkilauan","shimmering");
        setKata("berkilau","shiny");
        setKata("pendek","short");
        setKata("sakit","sick");
        setKata("bijaksana","thoughtful");
        setKata("hebat","terrific");
        setKata("tebal","thick");
        setKata("tipis, kurus","thin");
        setKata("rapi","tidy");
        setKata("gemuruh","thunderous");
        setKata("kecil, mungil","tiny");
        setKata("sulit, tabah","tough");
        setKata("tinggi","tall");
        setKata("banyak bicara","talkative");
        setKata("jinak","tame");
        setKata("lezat","tasty");
        setKata("tegang","tense");
        setKata("berterimakasih","thankful");
        setKata("haus","thirsty");
        setKata("jelek","ugly");
        setKata("tidak dapat diterima","unacceptable");
        setKata("rahasia","undercover, secret");
        setKata("tidak rata","uneven");
        setKata("tidak adil","unfair");
        setKata("kosong","vacant");
        setKata("sombong","vain");
        setKata("berharga","valuable");
        setKata("serbaguna","versatile");
        setKata("hangat","warm");
        setKata("bergelombang","wavy");
        setKata("lemah","weak");
        setKata("aneh","weird");
        setKata("basah","wet");
        setKata("seluruh","whole");
        setKata("jahat","wicked");
        setKata("lebar","wide");
        setKata("liar","wild");
        setKata("bijaksana","wise");
        setKata("usang","worn");
        setKata("lebih buruk","worse");
        setKata("muda","young");
        setKata("makan","eat");
        setKata("tidur","sleep");
        setKata("berdiri","stand up");
        setKata("duduk","sit down");
        setKata("berjalan","walk");
        setKata("minum","drink");
        setKata("menulis","write");
        setKata("membaca","read");
        setKata("mencuci","wash");
        setKata("bekerja","work");
        setKata("datang","come");
        setKata("bangun","wake up, get up");
        setKata("mandi","take a bath");
        setKata("kencing","take a pee");
        setKata("buang air besar","take a dump");
        setKata("berbicara","speak");
        setKata("mengobrol","talk");
        setKata("berpikir","think");
        setKata("menceritakan","tell");
        setKata("mendengarkan","listen");
        setKata("memakai","wear");
        setKata("menggunakan","use");
        setKata("menginginkan","want");
        setKata("pergi","go");
        setKata("memanggil","call");
        setKata("pergi kerja","go work");
        setKata("pulang","go home");
        setKata("belanja","go shopping");
        setKata("pacaran","date");
        setKata("mengerti","understand");
        setKata("batuk","cough");
        setKata("memasak","cook");
        setKata("menggoreng","fry");
        setKata("membeli","buy");
        setKata("menjual","sell");
        setKata("membayar","pay");
        setKata("membuka","open");
        setKata("menutup","close");
        setKata("memberi","give");
        setKata("memiliki","have");
        setKata("membuang","throw");
        setKata("menunjukkan","show");
        setKata("mengurangi","decrease");
        setKata("menambahkan","add");
        setKata("memotong","cut");
        setKata("menghubungkan","connect");
        setKata("tiba","arrive");
        setKata("meninggalkan","leave");
        setKata("mengingat","remember");
        setKata("bertanya","ask");
        setKata("jawaban","answer");
        setKata("membutuhkan","need");
        setKata("meletakkan","put");
        setKata("teriak","scream");
        setKata("berteriak","shout");
        setKata("menangis","cry");
        setKata("tertawa","laugh");
        setKata("tinggal","live");
        setKata("berdoa","pray");
        setKata("dorong","push");
        setKata("tarik","pull");
        setKata("mengajar","teach");
        setKata("belajar","study");
        setKata("menunggu","wait");
        setKata("menolong","help");
        setKata("berenang","swim");
        setKata("bertemu","meet");
        setKata("mengendarai","ride, drive");
        setKata("meminjam","borrow");
        setKata("meminjamkan","lend");
        setKata("mengembalikan","return");
        setKata("menemukan","find");
        setKata("menyembunyikan","hide");
        setKata("mengganggu","disturb");
        setKata("memotivasi","motivate");
        setKata("mencari","look for");
        setKata("melihat","look at, see");
        setKata("bersih","clean");
        setKata("menyapu","sweep");
        setKata("mengepel","mop");
        setKata("mengecat","paint");
        setKata("mengunjungi","visit");
        setKata("mengundang","invite");
        setKata("membuat","make");
        setKata("menyimpan","save");
        setKata("bergerak","move");
        setKata("wajah","face");
        setKata("membayangkan","imagine");
        setKata("menari","dance");
        setKata("menyanyi","sing");


        terjemahkanButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String inputText = tfkata.getText();

                if (getKata().containsKey(inputText)) {
                    takata.setText(kata.get(inputText));
                }else {
                    takata.setText(getKata().get(inputText));
                    JOptionPane.showMessageDialog(frame, inputText+" tidak ada di dalam kamus pintar");
                }
            }
        });

        keluarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int konfirmasi = JOptionPane.showConfirmDialog(keluar, "Apakah anda yakin ingin keluar?", "Silahkan pilih", JOptionPane.YES_NO_OPTION);
                if (konfirmasi == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(keluar, "Terimakasih telah menggunakan KAMUS PINTAR!");
                    System.exit(0);
                }
            }
        });

        tukarBahasaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EnglishIndonesia ei = new EnglishIndonesia();
                ei.showEngInd();
                frame.setVisible(false);
            }
        });
    }

    public static void showIndEng(){
        frame = new JFrame("Indonesia --> Inggris");
        frame.setContentPane(new IndonesiaEnglish().IndonesiaInggrisPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
       showIndEng();
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
